db=db.getSiblingDB('metadata');
db.addressable.remove({});
db.command.remove({});
db.device.remove({});
db.deviceProfile.remove({});
db.deviceReport.remove({});
db.deviceService.remove({});
db.provisionWatcher.remove({});
db.schedule.remove({});
db.scheduleEvent.remove({});
db=db.getSiblingDB('coredata')
db.valueDescriptor.remove({});
db.reading.remove({});
db.event.remove({});
db=db.getSiblingDB('logging')
db.logEntry.remove({});
db=db.getSiblingDB('scheduler')
db.interval.remove({});
db.intervalAction.remove({});
db=db.getSiblingDB('notifications')
db.notification.remove({});
db.subscription.remove({});
db.transmission.remove({});
db=db.getSiblingDB('exportclient')
db.exportconfiguration.remove({});
