version: '3.7'

services:
  app-service-blackbox-tests:
    image: ${REPOSITORY}/docker-app-service-configurable${ARCH}:${APP_SERVICE_VERSION}
    command: "-s -cp=consul.http://edgex-core-consul:8500 --registry --confdir=/res"
    ports:
      - 127.0.0.1:48095:48095/tcp
    container_name: app-service-blackbox-tests
    hostname: app-service-blackbox-tests
    env_file:
      - common.env
    environment:
      EDGEX_PROFILE: blackbox-tests
      SERVICE_HOST: app-service-blackbox-tests
      SERVICE_PORT: 48095
    depends_on:
      - consul
      - data
    networks:
      - edgex-network

  scalability-test-mqtt-export:
    image: ${REPOSITORY}/docker-app-service-configurable${ARCH}:${APP_SERVICE_VERSION}
    ports:
      - "48098:48098"
    container_name: scalability-test-mqtt-export
    hostname: scalability-test-mqtt-export
    env_file:
      - common.env
    environment:
      EDGEX_PROFILE: mqtt-export
      SERVICE_HOST: app-service-mqtt-export
      SERVICE_PORT: 48098
      WRITABLE_PIPELINE_EXECUTIONORDER: "TransformToJSON, MQTTSecretSend"
      WRITABLE_PIPELINE_FUNCTIONS_MQTTSECRETSEND_PARAMETERS_BROKERADDRESS: tcp://MQTT_BROKER_ADDRESS_PLACE_HOLDER:1883
      WRITABLE_PIPELINE_FUNCTIONS_MQTTSECRETSEND_PARAMETERS_TOPIC: edgex-events
      WRITABLE_LOGLEVEL: DEBUG
    depends_on:
      - consul
      - data
    networks:
      - edgex-network
