version: '3.7'

services:
  app-service-functional-tests:
    image: ${APP_SVC_REPOSITORY}/docker-app-service-configurable${ARCH}:${APP_SERVICE_VERSION}${APP_SVC_DEV}
    ports:
      - 48105:48105/tcp
    container_name: app-service-functional-tests
    hostname: app-service-functional-tests
    env_file:
      - common.env
    environment:
      EDGEX_PROFILE: functional-tests
      SERVICE_HOST: app-service-functional-tests
      SERVICE_PORT: 48105
    depends_on:
      - consul
      - data
    read_only: true
    networks:
      - edgex-network
    security_opt:
      - no-new-privileges:true
    user: "${EDGEX_USER}:${EDGEX_GROUP}"

  scalability-test-mqtt-export:
    image: ${APP_SVC_REPOSITORY}/docker-app-service-configurable${ARCH}:${APP_SERVICE_VERSION}${APP_SVC_DEV}
    ports:
      - "48106:48106"
    container_name: scalability-test-mqtt-export
    hostname: scalability-test-mqtt-export
    env_file:
      - common.env
    environment:
      EDGEX_PROFILE: mqtt-export
      SERVICE_HOST: app-service-mqtt-export
      SERVICE_PORT: 48106
      MESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-core-data
      WRITABLE_PIPELINE_EXECUTIONORDER: "TransformToJSON, MQTTSecretSend"
      WRITABLE_PIPELINE_FUNCTIONS_MQTTSECRETSEND_PARAMETERS_BROKERADDRESS: tcp://MQTT_BROKER_ADDRESS_PLACE_HOLDER:1883
      WRITABLE_PIPELINE_FUNCTIONS_MQTTSECRETSEND_PARAMETERS_TOPIC: edgex-events
      WRITABLE_LOGLEVEL: DEBUG
    depends_on:
      - consul
      - data
    read_only: true
    networks:
      - edgex-network
    security_opt:
      - no-new-privileges:true
    user: "${EDGEX_USER}:${EDGEX_GROUP}"
