version: '3.7'
volumes:
  PROFILE_VOLUME_PLACE_HOLDER:

services:
  device-virtual:
    image: ${REPOSITORY}/docker-device-virtual-go${ARCH}:${DEVICE_VIRTUAL_VERSION}
    ports:
    - 127.0.0.1:49990:49990/tcp
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      - edgex-network
    env_file:
      - common.env
    environment:
      SERVICE_HOST: edgex-device-virtual
    entrypoint: "/device-virtual"
    command: "--registry --confdir=CONF_DIR_PLACE_HOLDER"
    volumes:
      - PROFILE_VOLUME_PLACE_HOLDER:CONF_DIR_PLACE_HOLDER:z
    depends_on:
      - consul
      - data
      - command

  device-modbus:
    image: ${REPOSITORY}/docker-device-modbus-go${ARCH}:${DEVICE_MODBUS_VERSION}
    ports:
      - 127.0.0.1:49991:49991/tcp
    container_name: edgex-device-modbus
    hostname: edgex-device-modbus
    networks:
      - edgex-network
    env_file:
      - common.env
    environment:
      SERVICE_HOST: edgex-device-modbus
    entrypoint: "/device-modbus"
    command: "--registry --confdir=CONF_DIR_PLACE_HOLDER"
    volumes:
      - PROFILE_VOLUME_PLACE_HOLDER:CONF_DIR_PLACE_HOLDER:z
    depends_on:
      - consul
      - data
      - command
      - modbus-simulator
