version: '3.7'

services:
  vault-worker:
    environment:
      ADD_SECRETSTORE_TOKENS: ${TOKEN_LIST}

  app-service-http-export-secrets:
    image: ${REPOSITORY}/docker-app-service-configurable${ARCH}:${APP_SERVICE_VERSION}
    ports:
      - 127.0.0.1:48102:48102/tcp
    container_name: app-service-http-export-secrets
    hostname: app-service-http-export-secrets
    env_file:
      - common.env
      - common-security.env
    environment:
      EDGEX_PROFILE: http-export
      SERVICE_HOST: app-service-http-export-secrets
      SERVICE_PORT: 48102
      MESSAGEBUS_SUBSCRIBEHOST_HOST: edgex-core-data
      SECRETSTORE_PATH: /v1/secret/edgex/appservice-http-export-secrets/
      SECRETSTORE_TOKENFILE: /tmp/edgex/secrets/appservice-http-export-secrets/secrets-token.json
      WRITABLE_PIPELINE_FUNCTIONS_HTTPPOSTJSON_PARAMETERS_URL: http://EXPORT_HOST_PLACE_HOLDER:7770
      WRITABLE_PIPELINE_FUNCTIONS_HTTPPOSTJSON_PARAMETERS_SECRETHEADERNAME: ""
      WRITABLE_PIPELINE_FUNCTIONS_HTTPPOSTJSON_PARAMETERS_SECRETPATH: ""
      WRITABLE_LOGLEVEL: INFO # allows scripts to find and change with sed
    volumes:
    - /tmp/edgex/secrets/appservice-http-export-secrets:/tmp/edgex/secrets/appservice-http-export-secrets:ro,z
    depends_on:
      - consul
      - data
    read_only: true
    networks:
      - edgex-network
    security_opt:
      - no-new-privileges:true
